In [2]:
import numpy as np

list1 = [1, 2, 3, 4, 5]
np.array(list1)

array([1, 2, 3, 4, 5])

In [3]:
list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr1 = np.arange(0, 10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [8]:
arr3 = np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [9]:
arr3 * 5

array([5., 5., 5., 5., 5.])

In [15]:
arr4 = np.arange(0, 9)
arr4.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr5 = np.eye(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
arr6 = np.random.rand(2)
arr6

array([0.93947723, 0.78372031])

In [19]:
arr7 = np.random.randn(10)
arr7

array([ 0.56359505,  0.82917819, -0.44583492,  1.00846076,  0.0899733 ,
        0.30170066, -0.27120471, -0.73626198, -2.78942608,  0.0279882 ])

In [21]:
arr8 = np.random.randn(5, 5)
arr8

array([[ 0.44500248,  0.53144168,  0.19679821,  0.24819123, -1.08923604],
       [ 0.62138887, -0.38720275,  0.84133048, -0.32849446,  0.18384829],
       [-2.64793195, -1.45181864,  0.71137785, -1.88105138,  0.81297433],
       [ 0.26358425,  0.05070846,  0.47945094,  1.01793494, -1.72421702],
       [ 0.46069077,  0.44668063, -1.57170568,  0.3479571 , -0.40203752]])

In [22]:
arr9 = np.linspace(0, 1, 100)
arr9

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [26]:
arr10 = np.linspace(1, 100, 20)
arr10

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [27]:
arr10 / 100

array([0.01      , 0.06210526, 0.11421053, 0.16631579, 0.21842105,
       0.27052632, 0.32263158, 0.37473684, 0.42684211, 0.47894737,
       0.53105263, 0.58315789, 0.63526316, 0.68736842, 0.73947368,
       0.79157895, 0.84368421, 0.89578947, 0.94789474, 1.        ])

In [29]:
a = np.arange(1, 26).reshape(5, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
a[2:,:1]

array([[11],
       [16],
       [21]])

In [31]:
a[3:4, 4:]

array([[20]])

In [32]:
a[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [35]:
a[3, 4]

np.int64(20)

In [36]:
a[4:, 0:]

array([[21, 22, 23, 24, 25]])

In [37]:
a[3:, 0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
!pip install scipy

Defaulting to user installation because normal site-packages is not writeable


In [47]:
from scipy.linalg import svd

a = np.arange(1, 19).reshape(6, 3)
U, s, VT = svd(a)

In [48]:
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [49]:
s

array([4.58945322e+01, 1.64070530e+00, 1.74146424e-15])

In [50]:
VT

array([[-0.52903535, -0.57607152, -0.62310769],
       [-0.74394551, -0.03840487,  0.66713577],
       [ 0.40824829, -0.81649658,  0.40824829]])

In [51]:
U, s, VT = svd(a, full_matrices = True)
U

array([[-0.07736219,  0.71960032, -0.09075777, -0.25083666, -0.45979172,
        -0.4400296 ],
       [-0.19033085,  0.50893247,  0.58409372,  0.4022013 ,  0.06897105,
         0.44392965],
       [-0.3032995 ,  0.29826463, -0.34118019, -0.54123699,  0.50890998,
         0.38822268],
       [-0.41626816,  0.08759679, -0.61888418,  0.65636038,  0.03282454,
        -0.06437079],
       [-0.52923682, -0.12307105,  0.37872289, -0.04363171,  0.43069535,
        -0.61149707],
       [-0.64220548, -0.33373889,  0.08800553, -0.22285632, -0.58160921,
         0.28374512]])

In [52]:
U, s, VT = svd(a, full_matrices = False)
U

array([[-0.07736219,  0.71960032, -0.09075777],
       [-0.19033085,  0.50893247,  0.58409372],
       [-0.3032995 ,  0.29826463, -0.34118019],
       [-0.41626816,  0.08759679, -0.61888418],
       [-0.52923682, -0.12307105,  0.37872289],
       [-0.64220548, -0.33373889,  0.08800553]])

In [53]:
from numpy import diag
from numpy import dot

a = (U @ np.diag(s) @ VT)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])